### ISSUE TITLE
ZeroMemory

### ISSUE THREAD

**Issue by truepaddii** [BlauerKlappstuhl/Assignment#3]
**Describe the bug**
You've used ZeroMemory defines to clear the structs. This is an old method to do this. Nowadays we use an initializer list to clear these structs to zero.

**To Reproduce**
1. Go to https://github.com/BlauerKlappstuhl/Assignment/blob/db61a81d93ce6f15d3d0784b45f131ab69e4cd4a/Project1/Window.cpp#L48
2. See an example

**Expected behavior**
You should use initializer list style to clear the structs.
Additionally, this is more convenient.

**Additional Information**
Former `ZeroMemory(&wc, sizeof(WNDCLASSEX));` is legacy style.
Use `WNDCLASSEX wc = { 0 };` instead

**Comment by BlauerKlappstuhl** [comment]
Changed
