### ISSUE TITLE
 Too many members

### ISSUE THREAD

**Issue by truepaddii** [BlauerKlappstuhl/Assignment#4]
**Describe the bug**
You've used too many member properties. This inflates the class and makes it bigger in size. To optimize it, think about which properties it really needs as class members and which ones are ok to be stack local data.

**To Reproduce**
1. Go to https://github.com/BlauerKlappstuhl/Assignment/blob/db61a81d93ce6f15d3d0784b45f131ab69e4cd4a/Project1/Window.h#L40-L52
2. See the erroneous section

**Expected behavior**
The class should only carry needed members.

**Comment by BlauerKlappstuhl** [comment]
Reduced it from 7 member variables to 3
